import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,ClipboardList,Users,Boxes,HardHat,UserCircle,Settings,Search,Bell,Plus,LogOut,ShieldCheck,Trash2,RefreshCw}from"lucide-react";
import{supabase,isSupabaseConfigured}from"./lib/supabase";
import"./styles.css";

const nav=[["dashboard","דשבורד",LayoutDashboard],["orders","הזמנות",ClipboardList],["customers","לקוחות",Users],["inventory","מלאי",Boxes],["workers","עובדים",HardHat]];
const statusLabels={new:"חדש",production:"בייצור",cutting:"בחיתוך",ready:"מוכן לאספקה",delivery:"באספקה",completed:"הושלם",cancelled:"בוטל"};

function App(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadProfile(data.session.user.id);else setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadProfile(s.user.id);else{setProfile(null);setLoading(false)}});return()=>data.subscription.unsubscribe()},[]);
 async function loadProfile(id){const{data,error}=await supabase.from("profiles").select("*").eq("id",id).single();if(!error)setProfile(data);setLoading(false)}
 if(!isSupabaseConfigured)return <Setup/>;
 if(loading)return <div className="center"><RefreshCw className="spin"/>טוען מערכת...</div>;
 if(!session)return <Login/>;
 if(!profile)return <div className="center">הפרופיל עדיין נוצר. רענן את הדף.</div>;
 return <DashboardApp session={session} profile={profile}/>;
}

function Setup(){return <div className="login"><div className="login-card"><div className="brand-mark">א</div><h1>אבן פרימיום</h1><p>מערכת הניהול מחוברת לקוד, אך חסרים פרטי Supabase.</p><div className="setup-box">הוסף ב-GitHub Secrets/Environment את:<br/><b>VITE_SUPABASE_URL</b><br/><b>VITE_SUPABASE_PUBLISHABLE_KEY</b></div><a href="https://supabase.com" target="_blank">פתיחת Supabase</a></div></div>}

function Login(){async function google(){await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/-app/"}})}return <div className="login"><div className="login-card"><div className="brand-mark">א</div><h1>אבן פרימיום</h1><p>מערכת ניהול מפעל השיש</p><button className="google-btn" onClick={google}><b>G</b> כניסה באמצעות Google</button><small>הכניסה מאובטחת באמצעות Supabase Auth</small></div></div>}

function DashboardApp({session,profile}){
 const[page,setPage]=useState("dashboard"),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
 const title=nav.find(x=>x[0]===page)?.[1]||"הפרופיל שלי";
 const notify=x=>{setNotice(x);setTimeout(()=>setNotice(""),2500)};
 async function logout(){await supabase.auth.signOut()}
 return <div className="app" dir="rtl"><aside><div className="brand"><div className="brand-mark">א</div><div><b>אבן פרימיום</b><span>ניהול מפעל שיש</span></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?"active":""} onClick={()=>setPage(id)} key={id}><Icon size={19}/><span>{label}</span></button>)}{profile.role==="admin"&&<button className={page==="profile"?"active":""} onClick={()=>setPage("profile")}><UserCircle size={19}/><span>פרופיל והרשאות</span></button>}</nav><div className="side-bottom"><div className="mini-user"><div className="avatar">{(profile.full_name||session.user.email||"י")[0]}</div><div><b>{profile.full_name||"משתמש"}</b><span>{profile.role==="admin"?"מנהל":"עובד"}</span></div></div><button onClick={logout}><LogOut size={18}/><span>יציאה</span></button></div></aside><main><header><div><div className="crumb">אבן פרימיום / {title}</div><h1>{title}</h1></div><div className="head-actions"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש..." /></div><button className="icon-btn"><Bell size={19}/></button><div className="avatar">{(profile.full_name||"י")[0]}</div></div></header>{notice&&<div className="toast"><ShieldCheck size={18}/>{notice}</div>}{page==="dashboard"&&<Home setPage={setPage}/>} {page==="orders"&&<Orders profile={profile} query={query} notify={notify}/>} {page==="customers"&&<Customers profile={profile} query={query} notify={notify}/>} {page==="inventory"&&<Inventory profile={profile} query={query} notify={notify}/>} {page==="workers"&&<Workers profile={profile}/>} {page==="profile"&&<Profile profile={profile} session={session} notify={notify}/>}</main></div>
}

function Home({setPage}){const[stats,setStats]=useState({orders:0,customers:0,inventory:0});useEffect(()=>{(async()=>{const[a,b,c]=await Promise.all([supabase.from("orders").select("*",{count:"exact",head:true}),supabase.from("customers").select("*",{count:"exact",head:true}),supabase.from("inventory").select("*",{count:"exact",head:true})]);setStats({orders:a.count||0,customers:b.count||0,inventory:c.count||0})})()},[]);return <section><div className="welcome"><div><span className="eyebrow">מערכת מחוברת למסד נתונים</span><h2>ברוך הבא לאבן פרימיום 👋</h2><p>הנתונים נשמרים בענן ומוגנים בהרשאות משתמשים.</p></div><button className="primary" onClick={()=>setPage("orders")}><Plus size={18}/>הזמנה חדשה</button></div><div className="stats">{[["הזמנות",stats.orders,ClipboardList],["לקוחות",stats.customers,Users],["פריטי מלאי",stats.inventory,Boxes],["אבטחה","RLS",ShieldCheck]].map(([a,b,I])=><div className="stat" key={a}><div className="stat-top"><span>{a}</span><I size={19}/></div><strong>{b}</strong><small>{b==="RLS"?"הגנת מסד נתונים פעילה":"רשומות במסד הנתונים"}</small></div>)}</div><div className="card"><h3>המערכת מוכנה לעבודה</h3><p className="muted">בחר מהתפריט כדי לנהל הזמנות, לקוחות ומלאי. כל שינוי נשמר ישירות במסד הנתונים.</p></div></section>}

function Orders({profile,query,notify}){const[data,setData]=useState([]),[customers,setCustomers]=useState([]),[form,setForm]=useState({customer_id:"",product:"",amount:"",status:"new"});async function load(){const[{data:o},{data:c}]=await Promise.all([supabase.from("orders").select("*,customers(name)").order("created_at",{ascending:false}),supabase.from("customers").select("id,name").order("name")]);setData(o||[]);setCustomers(c||[])}useEffect(()=>{load()},[]);const rows=useMemo(()=>data.filter(x=>(x.product+" "+(x.customers?.name||"")+" "+x.order_number).includes(query)),[data,query]);async function add(e){e.preventDefault();const{error}=await supabase.from("orders").insert({customer_id:form.customer_id||null,product:form.product,amount:Number(form.amount)||0,status:form.status,created_by:(await supabase.auth.getUser()).data.user.id});if(error)notify(error.message);else{setForm({customer_id:"",product:"",amount:"",status:"new"});notify("ההזמנה נשמרה");load()}}async function remove(id){if(profile.role!=="admin")return notify("רק מנהל יכול למחוק הזמנות");const{error}=await supabase.from("orders").delete().eq("id",id);notify(error?error.message:"ההזמנה נמחקה");load()}return <section><form className="inline-form" onSubmit={add}><select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">בחר לקוח</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input required placeholder="מוצר / סוג שיש" value={form.product} onChange={e=>setForm({...form,product:e.target.value})}/><input required type="number" placeholder="סכום ₪" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><button className="primary"><Plus size={17}/>שמור הזמנה</button></form><div className="card"><div className="card-head"><div><h3>הזמנות</h3><span>{rows.length} רשומות אמיתיות במסד הנתונים</span></div></div><div className="table"><div className="tr th"><span>#</span><span>לקוח</span><span>מוצר</span><span>סכום</span><span>סטטוס</span>{profile.role==="admin"&&<span/>}</div>{rows.map(o=><div className="tr" key={o.id}><span className="bold">#{o.order_number}</span><span>{o.customers?.name||"—"}</span><span>{o.product}</span><span className="bold">₪{Number(o.amount).toLocaleString("he-IL")}</span><span><em className={o.status==="completed"?"green":"blue"}>{statusLabels[o.status]||o.status}</em></span>{profile.role==="admin"&&<button className="danger-icon" onClick={()=>remove(o.id)}><Trash2 size={15}/></button>}</div>)}</div></div></section>}

function Customers({profile,query,notify}){const[data,setData]=useState([]),[name,setName]=useState(""),[phone,setPhone]=useState("");async function load(){const{data,error}=await supabase.from("customers").select("*").order("created_at",{ascending:false});if(error)notify(error.message);else setData(data||[])}useEffect(()=>{load()},[]);const rows=data.filter(x=>(x.name+" "+x.phone+" "+x.customer_type).includes(query));async function add(e){e.preventDefault();const user=(await supabase.auth.getUser()).data.user;const{error}=await supabase.from("customers").insert({name,phone,created_by:user.id});if(error)notify(error.message);else{setName("");setPhone("");notify("הלקוח נשמר");load()}}return <section><form className="inline-form" onSubmit={add}><input required placeholder="שם לקוח" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="טלפון" value={phone} onChange={e=>setPhone(e.target.value)}/><button className="primary"><Plus size={17}/>לקוח חדש</button></form><div className="customer-grid">{rows.map(c=><div className="customer" key={c.id}><div className="customer-avatar">{c.name[0]}</div><div><h3>{c.name}</h3><span>{c.phone||"ללא טלפון"} · {c.customer_type}</span><strong>{new Date(c.created_at).toLocaleDateString("he-IL")}</strong></div></div>)}</div></section>}

function Inventory({profile,query,notify}){const[data,setData]=useState([]),[name,setName]=useState(""),[qty,setQty]=useState("");async function load(){const{data,error}=await supabase.from("inventory").select("*").order("name");if(error)notify(error.message);else setData(data||[])}useEffect(()=>{load()},[]);const rows=data.filter(x=>(x.name+" "+x.category).includes(query));async function add(e){e.preventDefault();if(profile.role!=="admin")return notify("רק מנהל יכול להוסיף מלאי");const{error}=await supabase.from("inventory").insert({name,quantity:Number(qty)||0});if(error)notify(error.message);else{setName("");setQty("");notify("פריט המלאי נשמר");load()}}async function update(id,quantity){if(profile.role!=="admin")return notify("רק מנהל יכול לשנות מלאי");const{error}=await supabase.from("inventory").update({quantity:Number(quantity)}).eq("id",id);if(error)notify(error.message);else load()}return <section>{profile.role==="admin"&&<form className="inline-form" onSubmit={add}><input required placeholder="שם חומר / שיש" value={name} onChange={e=>setName(e.target.value)}/><input type="number" placeholder="כמות" value={qty} onChange={e=>setQty(e.target.value)}/><button className="primary"><Plus size={17}/>הוסף למלאי</button></form>}<div className="inventory-grid">{rows.map(x=><div className="inventory" key={x.id}><div className="stone"></div><div><h3>{x.name}</h3><span>{x.category}</span></div>{profile.role==="admin"?<input className="qty" type="number" value={x.quantity} onChange={e=>update(x.id,e.target.value)}/>:<strong>{x.quantity}<small> יח׳</small></strong>}<em className={x.quantity<=x.min_quantity?"orange":"green"}>{x.quantity<=x.min_quantity?"נמוך":"תקין"}</em></div>)}</div></section>}

function Workers({profile}){return <section><div className="card"><h3>הרשאות עובדים</h3><p className="muted">הרשאות נאכפות במסד הנתונים באמצעות RLS.</p><div className="permission"><b>מנהל</b><span>גישה מלאה, מחיקה, ניהול מלאי והרשאות.</span></div><div className="permission"><b>עובד</b><span>צפייה בנתונים, יצירת הזמנות ולקוחות. ללא מחיקה וניהול מלאי.</span></div>{profile.role==="worker"&&<div className="notice">החשבון שלך מוגדר כעובד.</div>}</div></section>}

function Profile({profile,session,notify}){const[name,setName]=useState(profile.full_name||"");async function save(){const{error}=await supabase.from("profiles").update({full_name:name,updated_at:new Date().toISOString()}).eq("id",profile.id);notify(error?error.message:"הפרופיל נשמר")}return <section><div className="profile-card"><div className="profile-cover"></div><div className="profile-main"><div className="big-avatar">{(name||"י")[0]}</div><div className="profile-name"><h2>{name||"משתמש"}</h2><p>{profile.role==="admin"?"מנהל המערכת":"עובד"}</p></div></div><div className="profile-body"><div><h3>פרטים אישיים</h3><label>שם מלא<input value={name} onChange={e=>setName(e.target.value)}/></label><label>דוא״ל<input value={session.user.email||""} disabled/></label><button className="primary" onClick={save}>שמירת פרטים</button></div><div><h3>אבטחה</h3><div className="connection"><ShieldCheck/><div><b>Google / Supabase Auth</b><span>החשבון מאומת ומחובר בצורה מאובטחת.</span></div></div><div className="connection"><b>תפקיד במערכת</b><span>{profile.role==="admin"?"מנהל — הרשאות מלאות":"עובד — הרשאות מוגבלות"}</span></div></div></div></div></section>}

createRoot(document.getElementById("root")).render(<App/>);